# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6719e0c368f71220aa0fd08e00d081c5b69d44792324f0f6ccb41e436014fe40627d250dc54c9070c2ca338c25d359d6f045bdac8871165fea6a33de2a86c382

test:
  secret_key_base: f91ada1b0aee18a225b2e056a510e852d531e0a5e0542fb02f863a72be32400b0067f26faee479f5100244994ad288d5b89bc13ecb1d672b0d7f20c3d2b3282e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
